### ISSUE TITLE
Where are the files?

### ISSUE THREAD

**Issue by milani** [norc-labs/luabluez#1]
I only see a Makefile and README. Where is the `luamraa` or `test.lua`?

**Comment by mobileink** [comment]
hi milani,

Alas, I didn't get far with this before I got pulled in another direction.  I've uploaded the bit of code I wrote at the time in case you want to work on it.

Also luamraa is a separate project targeting https://github.com/intel-iot-devkit/mraa, not related to bluez.  It has about the same status as luabluez.

good luck,

Gregg

**Comment by milani** [comment]
@mobileink Thank you!
